- name: JinJa templates
  hosts: localhost
  connection: local
  vars:
    x: 11
    fruits:
      - apple
      - banana
    fruits_with_prices:
      - { name: apple, price: 11 }
      - { name: banana, price: 21 }
      - name: orange
        price: 600
  tasks:
    - name: copy
      copy:
        src: sample.txt
        dest: /tmp/s1.txt

    - name: template
      template:
        src: sample.txt
        dest: /tmp/s2.txt

